### ISSUE TITLE
Sweep: create missing test files

### ISSUE THREAD

**Issue by DebkanchanSamadder** [ride-app/driver-service#57]
create the following test files in the service directory and add testing boilerplate using github.com/onsi/ginkgo/v2 and github.com/onsi/gomega
- go_offline_test.go
- update_driver_test.go
- delete_driver_test.go
- get_location_test.go
- update_location_test.go
- get_vehicle_test.go
- update_vehicle_test.go
- get_status_test.go

<details>
<summary>Checklist</summary>

- [X] `service/go_offline_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "GoOffline" function tests

- [ ] `service/update_driver_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "UpdateDriver" function tests

- [X] `service/delete_driver_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "DeleteDriver" function tests

- [X] `service/get_location_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "GetLocation" function tests

- [X] `service/update_location_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "UpdateLocation" function tests

- [X] `service/get_vehicle_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "GetVehicle" function tests

- [X] `service/update_vehicle_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "UpdateVehicle" function tests

- [X] `service/get_status_test.go`
> * Add package declaration at the top of the file: `package service_test`
> • Import necessary packages for testing, including Ginkgo and Gomega
> • Set up a Describe block for "GetStatus" function tests

</details>

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by DebkanchanSamadder** [comment]
sweep: retry
